name: Create Release on Tag Push

on:
  push:
    paths: 'plugin.json'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # checkout
      - uses: actions/checkout@v4

      - name: Package
        run: find ./ -name 'icon.png' -o -name 'index.css' -o -name 'style.css' -o -name 'font-face.css' -o -name 'index.js' -o -name 'plugin.json' -o -name 'preview.png' -o -name 'README.md' -o -name 'README_zh_CN.md' -o -path './fonts/*' | xargs zip package.zip

      - name: Get version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq -r ".version" plugin.json'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: package.zip
          name: Release ${{ steps.version.outputs.value }}
          tag_name: ${{ steps.version.outputs.value }}
          make_latest: true
