name: Create Release on Tag Push

on:
  push:
    paths: 'plugin.json'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    premissions:
      contents: write
      packages: write

    steps:
      # checkout
      - uses: actions/checkout@v4

      - name: Package
        run: find ./ -name 'icon.png' -o -name 'index.css' -o -name 'index.js' -o -name 'plugin.json' -o -name 'preview.png' -o -name 'README.md' -o -name 'README_zh_CN.md' -o -name 'AlibabaPuHuiTi-3-65-Medium.woff' | xargs zip package.zip

      - name: Install requirements
        run: sudo apt-get install jq

      - name: Create tag
        run: echo "VERSION~$(jq -r ".version" plugin.json)" >> $GITHUB_ENV
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: package.zip
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          make_latest: true
